steps:
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'unit-tests'
    args: ['verify']
    dir: 'application'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args: ['build', '-t', 'gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA', '.']
    dir: 'application'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args: ['push', 'gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deployToFunc'
    args: ['beta', 'run', 'deploy', 'cloud-run-test-func', '--image=gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA', '--region=us-central1', '--platform=managed']
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'functional-tests'
    args: ['mvn', 'verify','-Dcucumber.options="--strict --tags @ft --plugin pretty classpath:features"',  '-Dtest=com.example.helloworld.RunCukesTest']
    dir: 'cucumber-tests'
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deployToInt'
    args: ['beta', 'run', 'deploy', 'cloud-run-test-int', '--image=gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA', '--region=us-central1', '--platform=managed']
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'integration-tests'
    args: ['mvn', 'verify','-Dcucumber.options="--strict --tags @ft --plugin pretty classpath:features"',  '-Dtest=com.example.helloworld.RunCukesTest']
    dir: 'cucumber-tests'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'pushToStable'
    args: ['push', 'gcr.io/pipeline-test-270210/cloud-run-test-stable:$SHORT_SHA']
