steps:
  - name: 'maven:3.5-jdk-8-alpine'
    id: 'unit-tests'
    args: ['mvn', 'verify']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA', '.']

