steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'cloud-run-test', '--image=gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA', '--region=us-central1', '--platform=managed']