steps:
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'unit-tests'
    args: ['verify']
    dir: 'application'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/pipeline-test-270210/cloud-run-test:$SHORT_SHA', '.']
    dir: 'application'

